apiVersion: apps/v1
kind: Deployment
metadata:
  name: facedetector
spec:
  selector:
    matchLabels:
      app: facedetector
  replicas: 1
  template:
    metadata:
      labels:
        app: facedetector
    spec:
      containers:
      - name: detector
        image: rochelleli/facedetector:v1
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0