apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor
spec:
  selector:
    matchLabels:
      app: image-process
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: image-process
    spec:
      hostNetwork: true
      containers:
      - name: image-process
        image: rochelleli/imageprocessor:v1
        # ports:
        # - containerPort: 1883